name: sanity-check PRs

on:
  # needs read/write GH token, do *not* execute arbitrary code from PR
  pull_request_target:
    paths:
      - '**.lean'

jobs:

  # Cancels previous runs of jobs in this file
  cancel:
    if: github.repository == 'leanprover-community/mathzoo'
    name: 'Cancel Previous Runs (CI)'
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  style_lint:
    if: github.repository == 'leanprover-community/mathzoo'
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: install Python
        if: ${{ 'ubuntu-latest' == 'ubuntu-latest' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: lint
        run: |
          bash ./scripts/lint-style.sh

  build:
    if: github.repository == 'leanprover-community/mathzoo'
    name: Build (changed) Lean files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo "short_lean_version=$(~/.elan/bin/lean --run scripts/lean_version.lean)" >> $GITHUB_ENV

      - name: install leanproject
        run: |
          set -o pipefail
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          source ~/.profile
          pipx install mathlibtools

      - name: install Python
        if: ${{ ! 1 }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: build (changed) files
        id: build
        run: |
          leanpkg configure
          leanproject get-mathlib-cache
          git fetch --depth=1 origin main
          echo "::set-output name=started::true"
          bash ./scripts/build_new_files.sh

      - name: clean up working directory and elan
        if: always() && ${{ 1 }}
        run: rm -rf * $HOME/.elan

  final:
    name: Post-CI job
    if: github.repository == 'leanprover-community/mathzoo'
    needs: [style_lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: PR
        uses: 8BitJonny/gh-get-current-pr@1.2.0
        # TODO: this may not work properly if the same commit is pushed to multiple branches:
        # https://github.com/8BitJonny/gh-get-current-pr/issues/8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Only return if PR is still open
          filterOutClosed: true

      - id: remove_labels
        name: Remove "awaiting-CI"
        # we use curl rather than octokit/request-action so that the job won't fail
        # (and send an annoying email) if the labels don't exist
        run: |
          curl --request DELETE \
            --url https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.PR.outputs.number }}/labels/awaiting-CI \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'          